apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  servicename: mongodb-headless-svc
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
  template:
    metadata:
      labels:
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb
          ports:
            containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo-password
          volumeMounts:
            - name: database-persistent-volume-claim
              mountPath: mongodb/data
