apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: node-rest
  template:
    metadata:
      labels:
        component: node-rest
    spec:
      containers:
        - name: node-rest-container
          image: gaganshera/nagp-2021-node-devops-app
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - name: http 
              containerPort: 3010          
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: node-rest-service-np
spec:
  type: LoadBalancer
  ports:
    - port: 3010
      targetPort: 3010
      nodePort: 30080
  selector:
    component: node-rest
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-app-rest-api-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app-rest-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5