apiVersion: v1
kind: Service
metadata:
  name: node-rest-service-np
spec:
  type: LoadBalancer
  ports:
    - port: 3010
      targetPort: 3010
      nodePort: 30080
  selector:
    component: node-rest